package com.softusing.hejunjie.mapper;

import com.softusing.hejunjie.entity.Book;
import com.softusing.hejunjie.entity.BookExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    @Delete({
            "delete from book",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    @Insert({
            "insert into book (author, description, ",
            "name, status)",
            "values (#{author,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
            "#{name,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    int insertSelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    @Select({
            "select",
            "id, author, description, name, status",
            "from book",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.softusing.hejunjie.mapper.BookMapper.BaseResultMap")
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    int updateByExampleSelective(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    int updateByExample(@Param("row") Book row, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    int updateByPrimaryKeySelective(Book row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu May 11 11:06:07 JST 2023
     */
    @Update({
            "update book",
            "set author = #{author,jdbcType=VARCHAR},",
            "description = #{description,jdbcType=VARCHAR},",
            "name = #{name,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=INTEGER}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Book row);

    //mybatis接口
    List<Book> queryBooksByArray();

}